baseURL = "https://suchinton.github.io/"
languageCode = "en-us"
title = "Suchinton's Hub 🚀"
theme = "digitalgarden"

[Params]
  description = "Suchinton's Blog Post Website"
  images = ['/digital-garden-logo.png']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = "About"
  url = '/About'
  weight = 4
[[menu.main]]
  name = "GSoC '23 Blog"
  url = '/articles'
  weight = 4
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 5

[[menu.main]]
  name = 'GSoC links'
  params.header = true
  weight = 6
[[menu.main]]
  name = 'Acceptance Letter'
  url = 'https://drive.google.com/file/d/1KM2ecIOdOfODWEzUHujxUlFb_73a9f91/view?usp=share_link'
  weight = 7
[[menu.main]]
  name = 'Proposal'
  url = 'https://drive.google.com/file/d/1vix6iTDAy-HU---iU0tdi86pUtZtE-_t/view?usp=sharing'
  weight = 8
[[menu.main]]
  name = 'Project'
  url = 'https://github.com/suchinton/AGL_Demo_Control_Panel'
  weight = 9


[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/suchinton'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/suchinton-chakravarty/'
  weight = 2
[[menu.social]]
  name = 'Instagram'
  url = 'https://www.instagram.com/suchinton_never_/'
  weight = 3
[[menu.social]]
  name = 'Email'
  url = 'mailto:suchinton.2001@gmail.com'
  weight = 5
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 6


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
